(source gnu)
(source melpa)


(depends-on "cask")


(depends-on "projectile")
(depends-on "projectile-rails")
(depends-on "helm-projectile")
(depends-on "helm-ag")

(depends-on "enh-ruby-mode")
(depends-on "rubocop")
(depends-on "inf-ruby")
(depends-on "company-inf-ruby")
(depends-on "fill-column-indicator")
(depends-on "robe")


(depends-on "color-theme")
(depends-on "zenburn-theme")
(depends-on "highlight")
(depends-on "highlight-indentation")

(depends-on "avy")

(depends-on "google-translate")

(depends-on "web-mode")
(depends-on "flycheck")
(depends-on "ruby-electric")
(depends-on "ruby-block")
(depends-on "anzu")
(depends-on "ruby-refactor")
(depends-on "smart-compile")

(depends-on "auto-complete")
(depends-on "company")
(depends-on "dired+")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "feature-mode")
(depends-on "haml-mode")
(depends-on "haskell-mode")
(depends-on "iflipb")
(depends-on "js3-mode")
(depends-on "json-mode")
(depends-on "multi-term")
(depends-on "multiple-cursors")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "rainbow-mode")
(depends-on "s")
(depends-on "shut-up")
(depends-on "simple-httpd")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "yaml-mode")
(depends-on "yasnippet")
(depends-on "ecukes")
(depends-on "magit")
(depends-on "discover")
(depends-on "restclient")
(depends-on "json-reformat")
(depends-on "scion")
(depends-on "emamux")
(depends-on "w3m")
(depends-on "helm")
(depends-on "fuzzy")
(depends-on "fuzzy-match")
(depends-on "sass-mode")
(depends-on "ace-window")
(depends-on "slime")
(depends-on "flycheck")

